[features]
seeds = false
[programs.localnet]
coin_flip = "AmTdGr7b7cissZ2fVPnKuDnJieHhTFpNntdsSEbu7qFK"

[programs.devnet]
coin_flip = "AmTdGr7b7cissZ2fVPnKuDnJieHhTFpNntdsSEbu7qFK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
